name: Compress on version tag

on:
  push:
    tags:
      - "*-v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set filename
        id: vars
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          TAG_NAME="${GITHUB_REF_NAME}"
          MC_VERSION="${TAG_NAME%%-*}"
          RELEASE_VERSION="${TAG_NAME#*-}"
          PACKNAME="${REPO_NAME}-${RELEASE_VERSION}-mc${MC_VERSION}"
          FILENAME="${PACKNAME}.zip"
          echo "MC_VERSION=$MC_VERSION" >> $GITHUB_ENV
          echo "PACKNAME=$PACKNAME" >> $GITHUB_ENV
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Create ZIP archive
        run: |
          zip -r "$FILENAME" . \
          -x ".git/*" ".github/*" "example/*" ".gitignore" "NEWCHANGES.txt"

      - name: Read changelog
        id: read_changelog
        run: |
          {
            printf 'content<<EOF\n'
            cat NEWCHANGES.txt
            printf '\nEOF\n'
          } >> "$GITHUB_OUTPUT"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.FILENAME }}"
          body_path: NEWCHANGES.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Modrinth Release
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: AeTvZxVy
          name: ${{ env.PACKNAME }}
          version: ${{ env.RELEASE_VERSION }}
          changelog: ${{ steps.read_changelog.outputs.content }}
          loaders: '["datapack"]'
          files: '["${{ env.FILENAME }}"]'
          game-versions: '["${{ env.MC_VERSION }}"]'
